apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argos-service.fullname" . }}-secret 
data:
  {{- with .Values.aad }}
  jwt.token.secret: {{ .jwt_token | b64enc |  quote }}
  azure-client-secret: {{ .client_secret | b64enc |  quote }}
  azure-client-id: {{ .client_id | b64enc |  quote }}
  azure.authorizationUri: {{ list .client_provider_auth_url_prefix "/" .authorizationUri | join "" | b64enc |  quote }}
  azure.tokenUri: {{ list .client_provider_token_url_prefix "/" .tokenUri | join "" | b64enc |  quote }}
  {{- end }}
  mongodb-uri: {{ with .Values.secret.mongodb_uri -}}
  {{- list "mongodb://" .username ":" .password "@" $.Release.Name "-" .dbchart ":" .dbport "/" .dbconn | join ""  | b64enc |  quote }}
# {{- ( printf "%s%s:%s@%s-%s%s" "mongodb://" .username .password $.Release.Name "database" ":27017/guestbook?authSource=admin" ) | b64enc | quote }}
{{- end }}
