#
# Copyright (C) 2019 - 2020 Rabobank Nederland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.1'

services:
  argos-frontend:
    image: argosnotary/argos-frontend:0.0.1-RC8
    environment:
      - BACKEND_URL=http://argos-service:8080
    ports:
      - 80:80

  argos-service:
    image: argosnotary/argos-service:0.0.1-RC8
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/test
      spring.security.oauth2.client.registration.azure.clientId: client-id
      spring.security.oauth2.client.registration.azure.clientSecret: client-secret
      spring.security.oauth2.client.provider.azure.authorizationUri: http://localhost:8087/oauth2/v2.0/authorize
      spring.security.oauth2.client.provider.azure.tokenUri: http://oauth-stub:8080/oauth2/v2.0/token
      spring.security.oauth2.client.provider.azure.userInfoUri: http://oauth-stub:8080/v1.0/me
      jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
      auth.frontendRedirectBasePath: http://localhost
      server.use-forward-headers: 'true'
    ports:
      - 8080:8080
      
  oauth-stub:
    image: argosnotary/argos-integration-test-stub:0.0.1-RC8
    ports:
      - 8087:8080

  mongodb:
    image: mongo:4.2.8-bionic
    command: --replSet rs0
    volumes:
      - ./docker/replica-init.js:/docker-entrypoint-initdb.d/replica-init.js
    ports:
      - 27017:27017
