apiVersion: v2
name: argos
version: 0.0.1-RC7
description: Argos Notary
home: https://argosnotary.github.io
keywords:
  - argos
  - notary
type: application
sources:
  - https://github.com/argosnotary
dependencies:
  - name: mongodb
    version: 7.14.0
    repository: https://charts.bitnami.com/bitnami
  - name: oauth-stub
    version: 0.0.1-RC7
    condition: oauth-stub.enabled
maintainers:
  - name: Gerard Borst
  - name: Michel Durieux
  - name: Bart Kors
appVersion: 0.0.1-RC7
