apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argos-frontend.fullname" . }}-configmap
data:
  backend-url: {{ list "http://" .Release.Name "-argos-service:8080" | join "" |  quote }}
  server-name: foo
  nginx-conf-template: "
    \ server {\n
    \    listen  80;\n
    \    access_log /dev/stdout;\n
    \    error_log /dev/stderr;\n
    \    server_tokens off;\n
    \    add_header 'strict-transport-security' 'max-age=157680000 ; includeSubDomains' always;\n
    \    add_header 'X-Frame-Options' 'SAMEORIGIN' always;\n
    \    add_header 'X-Content-Type-Options' 'nosniff' always;\n
    \    add_header 'X-XSS-Protection' '1; mode=block';\n
    \    add_header 'X-UA-Compatible' 'IE=edge';\n
    \    location / {\n
    \       root /usr/share/nginx/html;\n
    \       index index.html index.htm;\n
    \       try_files $uri $uri/ /index.html =404;\n    }\n
    \    location /api/ {\n
    \       proxy_pass ${BACKEND_URL};\n
    \       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \       proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;\n
    \       proxy_set_header Host $host;\n
    \    }\n
    \    location /actuator/ {\n
    \       proxy_pass ${BACKEND_URL};\n
    \       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \       proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;\n
    \       proxy_set_header Host $host;\n
    \  }\n}\n"